import {clamp,lerp,done,TAU} from '../draw.js';
const pos=i=>({x:270+(i%3)*180,y:800+Math.floor(i/3)*118});
function scene(d,level,u,x,y,scale=1){const c=d.c;c.save();c.translate(x,y);c.scale(scale,scale);d.line({x:-185,y:65},{x:185,y:65},'#918668',5);if(level===0){d.ring(0,0,50,'#d4b279',4);d.animal(-150+u*300,30-Math.sin(u*Math.PI)*130,'rabbit',1.25,u*6);}else if(level===1){d.leaf(-150,60,-Math.PI/3,75);d.animal(-140+u*280,20-Math.sin(u*Math.PI)*90,'bird',1.3,u*12);d.envelope(50,40-clamp((u-.45)*150,0,100),14,'#ebd5ad','♥');}else{const x=-140+(u<.5?u*560:(1-u)*560);d.ring(140,20,25);d.animal(x,40,'fox',1.1,u*8);if(u>.5){d.ring(x+42,26,9,'#d2ad62',3);d.line({x:x+48,y:33},{x:x+65,y:48},'#d8b265',4);}else{d.ring(135,37,9,'#d2ad62',3);d.line({x:141,y:42},{x:159,y:55},'#d8b265',4);}}c.restore();}
function choose(s,i){if(s.picked===null){s.picked=i;s.selected=i;}else{[s.order[i],s.order[s.picked]]=[s.order[s.picked],s.order[i]];s.picked=null;s.selected=i;s.swaps++;s.note='Run the reel and watch the movement.';}}
export default{
 title:'The Missing Frames',intro:'Milo has dropped tomorrow’s moving picture. Put the scraps of film back in sequence and turn a jittery jumble into one lovely little story.',
 instructions:'Tap one film frame, then another to swap them. Watch the large moving scene above; it follows your edited sequence. The story runs left-to-right, then down the rows. Arrows choose a frame, Space selects it, Enter runs the reel. A helpful splice places one frame if you get stuck.',
 levels:['The rabbit and the moon','The flying post','A fox and a borrowed key'],actions:[{id:'play',label:'Run the reel'},{id:'choose',label:'Select chosen frame'},{id:'hint',label:'One helpful splice'}],
 create(level,rng){const n=level===0?6:9,order=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=Math.floor(rng()*(i+1));[order[i],order[j]]=[order[j],order[i]];}if(order.every((v,i)=>v===i))order.reverse();return{level,order,selected:0,picked:null,swaps:0,t:0,reel:0,checking:false,note:'The reel is out of order.'};},
 update(s,dt){s.t+=dt;s.reel+=dt;if(s.checking&&s.reel>5){s.checking=false;if(s.order.every((v,i)=>v===i))done(s,'The picture moves again','A whole little story restored in '+s.swaps+' splices. Milo is saving you a seat at the premiere.');else s.note='There is still a jump in the story. Follow the animal’s movement and what it carries.';}},
 pointer(s,type,p){if(type!=='down')return;const i=s.order.findIndex((_,i)=>{const q=pos(i);return Math.abs(p.x-q.x)<79&&Math.abs(p.y-q.y)<48;});if(i>=0)choose(s,i);},
 action(s,id){if(id==='play'){s.reel=0;s.checking=true;}if(id==='choose')choose(s,s.selected);if(id==='hint'){const i=s.order.findIndex((v,i)=>v!==i);if(i>=0){const j=s.order.indexOf(i);[s.order[i],s.order[j]]=[s.order[j],s.order[i]];s.selected=i;s.picked=null;s.swaps++;}}},
 key(s,k,down){if(!down)return;if(k===' ')choose(s,s.selected);else if(k==='Enter')this.action(s,'play');else{const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-3,ArrowDown:3}[k];if(delta)s.selected=clamp(s.selected+delta,0,s.order.length-1);}},
 draw(s,d){const n=s.order.length,f=(s.reel%5)/5*(n-1),i=Math.floor(f),u=lerp(s.order[i],s.order[Math.min(i+1,n-1)],f-i)/(n-1);
  d.poly([[210,430],[690,430],[690,710],[210,710]],'#e9d6b180','#b59b6e',4);scene(d,s.level,u,450,590,1.05);
  for(let j=0;j<n;j++){const p=pos(j);d.poly([[p.x-80,p.y-50],[p.x+80,p.y-50],[p.x+80,p.y+50],[p.x-80,p.y+50]],'#4d4237','#bfa273',2);d.poly([[p.x-68,p.y-37],[p.x+68,p.y-37],[p.x+68,p.y+37],[p.x-68,p.y+37]],'#dbc6a2',null);scene(d,s.level,s.order[j]/(n-1),p.x,p.y,.34);for(let x=-64;x<70;x+=22){d.circle(p.x+x,p.y-44,3,'#e9d5ad');d.circle(p.x+x,p.y+44,3,'#e9d5ad');}if(j===s.selected||j===s.picked)d.poly([[p.x-83,p.y-53],[p.x+83,p.y-53],[p.x+83,p.y+53],[p.x-83,p.y+53]],null,j===s.picked?'#f6dd8f':'#bc886b',3);}
  for(const x of [230,670]){d.ring(x,360,34,'#b9955f',5);for(let j=0;j<5;j++){const a=j*TAU/5+s.reel;d.circle(x+Math.cos(a)*20,360+Math.sin(a)*20,7,'#665440');}d.circle(x,360,5,'#e8c888');}},
 readout:s=>s.swaps+' splices · Frame '+(s.selected+1)+' selected · '+s.note
};
