import {clamp,done} from '../draw.js';
const puzzles=[['AABB','ACCB','ACDB','DDDD'],['AAABB','ACCBB','ADCEE','DDDEE'],['AABBB','AACBD','ECCDD','EECFD','EEFFF']];
const colours=['#9eab83','#b98678','#d5bd82','#87aaa2','#a099b7','#c3a071'],names=['Folded coat','Velvet slippers','Telescope wrap','Map satchel','Silk umbrella','Lantern pouch'];
function normal(cells){const mx=Math.min(...cells.map(c=>c[0])),my=Math.min(...cells.map(c=>c[1]));return cells.map(([x,y])=>[x-mx,y-my]);}
function rotate(p){p.cells=normal(p.cells.map(([x,y])=>[-y,x]));}
function valid(s,p,x,y){return p.cells.every(([cx,cy])=>{const a=x+cx,b=y+cy;return a>=0&&b>=0&&a<s.w&&b<s.h&&!s.pieces.some(q=>q!==p&&q.place&&q.cells.some(([qx,qy])=>q.place.x+qx===a&&q.place.y+qy===b));});}
function choose(s,p){s.active=p.id;s.ghost={x:1,y:1};s.note=names[p.id]+': turn it, then find a snug place.';}
function place(s){const p=s.pieces[s.active];if(!p||p.place)return;if(valid(s,p,s.ghost.x,s.ghost.y)){p.place={...s.ghost};s.moves++;s.note='A snug fit. Nothing squashed.';if(s.pieces.every(p=>p.place))done(s,'The impossible suitcase closes','Every treasure has its own little place. Packed in '+s.moves+' placements. Kit can finally catch the midnight train.');}else s.note='That overlaps a treasure or the leather edge. Try another turn.';}
function tray(i){return{x:230+(i%3)*205,y:965+Math.floor(i/3)*133};}
function selectNext(s){let i=s.active;for(let n=0;n<s.pieces.length;n++){i=(i+1)%s.pieces.length;if(!s.pieces[i].place){choose(s,s.pieces[i]);return;}}}
function item(d,p,x,y,size,alpha=1){const c=d.c;c.save();c.globalAlpha=alpha;const contains=(x,y)=>p.cells.some(a=>a[0]===x&&a[1]===y);for(const [cx,cy] of p.cells){const a=x+cx*size,b=y+cy*size;d.poly([[a+4,b+9],[a+size+3,b+9],[a+size+3,b+size+8],[a+4,b+size+8]],'#302c2540');d.poly([[a+2,b+2],[a+size-2,b+2],[a+size-2,b+size-2],[a+2,b+size-2]],colours[p.id]);for(const [dx,dy,x1,y1,x2,y2] of [[0,-1,a,b,a+size,b],[1,0,a+size,b,a+size,b+size],[0,1,a,b+size,a+size,b+size],[-1,0,a,b,a,b+size]])if(!contains(cx+dx,cy+dy)){d.line({x:x1,y:y1},{x:x2,y:y2},'#e8d6a2',3);}}const [cx,cy]=p.cells[Math.floor(p.cells.length/2)],a=x+(cx+.5)*size,b=y+(cy+.5)*size;d.circle(a,b,size*.22,'#f4e8c477','#746348',1);if(p.id%3===0)d.star(a,b,size*.15,'#715d3c');else if(p.id%3===1)d.heart(a,b,size*.15,'#715d3c');else{d.arc(a,b,size*.16,Math.PI,0,'#715d3c',2);d.line({x:a,y:b},{x:a,y:b+size*.17},'#715d3c',2);}c.restore();}
export default{
 title:'The Impossible Suitcase',intro:'Kit promised to pack lightly. Kit brought a telescope. Folded treasures, a leather case and a very particular midnight departure.',
 instructions:'Drag treasures from the shelf into the suitcase. Rotate turns the selected treasure; it must fit without overlaps. You can lift packed pieces back out. Keyboard: arrows move the preview, R rotates, Enter places. Next treasure selects another. Kit’s sketch shows where one piece could go.',
 levels:['A small overnight case','Just one more thing','The midnight expedition'],actions:[{id:'rotate',label:'Rotate · R'},{id:'place',label:'Tuck it in · Enter'},{id:'next',label:'Next treasure'},{id:'lift',label:'Unpack selected'},{id:'hint',label:'Kit’s sketch'}],
 create(level){const grid=puzzles[level],w=grid[0].length,h=grid.length,size=420/w,letters=[...new Set(grid.join(''))].sort(),pieces=letters.map((letter,id)=>{const cells=[];grid.forEach((row,y)=>[...row].forEach((v,x)=>{if(v===letter)cells.push([x,y]);}));const origin={x:Math.min(...cells.map(c=>c[0])),y:Math.min(...cells.map(c=>c[1]))},p={id,cells:normal(cells),original:normal(cells),origin,place:null};for(let r=0;r<(id+level+1)%4;r++)rotate(p);return p;});return{level,w,h,size,x:240,y:435,pieces,active:0,ghost:{x:0,y:0},drag:null,moves:0,hint:0,note:'Every case has a complete solution; nothing needs to be forced.'};},
 update(s,dt){s.hint=Math.max(0,s.hint-dt);},
 pointer(s,type,p){if(type==='cancel'){if(s.drag){const q=s.pieces[s.active];q.place=s.drag.before;q.cells=s.drag.cells;s.drag=null;}return;}if(type==='down'){for(const q of [...s.pieces].reverse()){if(q.place){const gx=Math.floor((p.x-s.x)/s.size)-q.place.x,gy=Math.floor((p.y-s.y)/s.size)-q.place.y;if(q.cells.some(c=>c[0]===gx&&c[1]===gy)){const before=q.place;choose(s,q);s.ghost={...before};q.place=null;s.drag={before,cells:q.cells.map(c=>[...c]),off:{x:gx+.5,y:gy+.5}};return;}}else{const t=tray(q.id);if(Math.abs(p.x-t.x)<93&&Math.abs(p.y-t.y)<59){choose(s,q);s.drag={before:null,cells:q.cells.map(c=>[...c]),off:{x:.5,y:.5}};return;}}}}if((type==='move'||type==='up')&&s.drag){s.ghost={x:Math.round((p.x-s.x)/s.size-s.drag.off.x),y:Math.round((p.y-s.y)/s.size-s.drag.off.y)};if(type==='up'){place(s);s.drag=null;}}},
 action(s,id){const p=s.pieces[s.active];if(id==='rotate'){if(p.place){s.ghost={...p.place};p.place=null;}rotate(p);}if(id==='place')place(s);if(id==='next')selectNext(s);if(id==='lift'&&p.place){s.ghost={...p.place};p.place=null;}if(id==='hint')s.hint=5;},
 key(s,k,down){if(!down)return;if(k==='r')this.action(s,'rotate');if(k==='Enter')place(s);if(k.startsWith('Arrow')){const p=s.pieces[s.active];if(p.place){s.ghost={...p.place};p.place=null;}s.ghost.x=clamp(s.ghost.x+(k==='ArrowRight'?1:k==='ArrowLeft'?-1:0),0,s.w-1);s.ghost.y=clamp(s.ghost.y+(k==='ArrowDown'?1:k==='ArrowUp'?-1:0),0,s.h-1);}},
 draw(s,d){const w=s.w*s.size,h=s.h*s.size,x=s.x,y=s.y;d.poly([[x-24,y-16],[x+w+24,y-16],[x+w+24,y+h+24],[x-24,y+h+24]],'#684c36','#c2a078',8);d.poly([[x-17,y-110],[x+w+17,y-110],[x+w+24,y-30],[x-24,y-30]],'#866749','#c2a078',6);d.path([{x:400,y:y-113},{x:400,y:y-134},{x:500,y:y-134},{x:500,y:y-113}],'#725233',10);d.text('KIT’S MIDNIGHT CASE',450,y-65,18,'#e9d7a8');d.poly([[x,y],[x+w,y],[x+w,y+h],[x,y+h]],'#d4c8a0','#eee0ba',3);for(let a=0;a<=s.w;a++)for(let b=0;b<=s.h;b++)d.circle(x+a*s.size,y+b*s.size,1.5,'#9e9475');for(const q of s.pieces)if(q.place)item(d,q,x+q.place.x*s.size,y+q.place.y*s.size,s.size);
  const p=s.pieces[s.active];if(p&&!p.place){const ok=valid(s,p,s.ghost.x,s.ghost.y);item(d,p,x+s.ghost.x*s.size,y+s.ghost.y*s.size,s.size,.53);d.text(ok?'A little room here':'Not quite a fit',450,y+h+60,18,ok?'#365947':'#6d3f31');}for(const q of s.pieces){const t=tray(q.id);d.ellipse(t.x,t.y+38,75,13,'#28312622');if(q.place){d.text('✓ packed',t.x,t.y,17,'#e4d7b5');continue;}const spanX=Math.max(...q.cells.map(c=>c[0]))+1,spanY=Math.max(...q.cells.map(c=>c[1]))+1,small=Math.min(36,150/spanX,88/spanY);item(d,q,t.x-spanX*small/2,t.y-spanY*small/2,small);if(q.id===s.active)d.ellipse(t.x,t.y+51,68,8,null,'#e6ca8a',2);}
  if(s.hint){const c=d.c;c.save();c.setLineDash([8,5]);for(const [cx,cy] of p.original){const a=x+(cx+p.origin.x)*s.size,b=y+(cy+p.origin.y)*s.size;d.poly([[a+4,b+4],[a+s.size-4,b+4],[a+s.size-4,b+s.size-4],[a+4,b+s.size-4]],'#fff5b122','#705633',3);}c.restore();}},
 readout:s=>s.pieces.filter(p=>p.place).length+' / '+s.pieces.length+' treasures packed · '+s.note
};
