// Catalogue ids used as play pieces and chapter prizes. Paths match the
// transparent turnaround pack. Workshop play never writes the pocket.
export const items = {
  'everyday-penny': {collection:'pennies', name:'Everyday penny'},
  'moon-penny': {collection:'pennies', name:'Moon penny'},
  'rose-penny': {collection:'pennies', name:'Rose penny'},
  'star-token': {collection:'pennies', name:'Star token'},
  'crown-token': {collection:'pennies', name:'Crown token'},
  'penny-purse': {collection:'pennies', name:'Penny purse'},
  'coin-sleeve': {collection:'gift-wrapping', name:'Coin sleeve'},
  'copper-cascade': {collection:'game-prizes', name:'Copper cascade'},
  'penny-tree': {collection:'game-prizes', name:'Penny tree'},
  'trade-envelope': {collection:'gift-wrapping', name:'Trade envelope'},
  'sealed-secret': {collection:'alley-curios', name:'Sealed secret'},
  'return-postcard': {collection:'tickets', name:'Return postcard'},
  'message-bottle': {collection:'future-curios', name:'Message bottle'},
  'charm-pouch': {collection:'gift-wrapping', name:'Charm pouch'},
  'whisper-charm': {collection:'alley-curios', name:'Whisper charm'},
  'secret-keeper': {collection:'parlour-prizes', name:'Secret keeper'},
  'ticket-satchel': {collection:'wearables', name:'Ticket satchel'},
  'lucky-match': {collection:'alley-curios', name:'Lucky match'},
  'pressed-heart': {collection:'alley-curios', name:'Pressed heart'},
  'pocket-observatory': {collection:'parlour-prizes', name:'Pocket observatory'},
  'penny-collector-book': {collection:'collector-books', name:'Penny collector book'},
  'night-suitcase': {collection:'garden-prizes', name:'Night suitcase'},
  'heart-biscuit': {collection:'sweet-treats', name:'Heart biscuit'},
  'rose-hair-bow': {collection:'wearables', name:'Rose hair bow'},
  'rose-press': {collection:'parlour-prizes', name:'Rose press'},
  'rose-lockbox': {collection:'parlour-prizes', name:'Rose lockbox'},
  'clockwork-key': {collection:'machine-curios', name:'Clockwork key'},
  'cabinet-key': {collection:'parlour-prizes', name:'Cabinet key'},
  'heart-gear': {collection:'machine-curios', name:'Heart gear'},
  'display-dome': {collection:'gift-wrapping', name:'Display dome'},
  'clockwork-butterfly': {collection:'future-curios', name:'Clockwork butterfly'},
  'crowned-duck': {collection:'garden-prizes', name:'Crowned duck'},
  'brave-try-ribbon': {collection:'awards', name:'Brave-try ribbon'},
  'lucky-dish': {collection:'garden-prizes', name:'Lucky dish'},
  'moon-lantern': {collection:'parlour-prizes', name:'Moon lantern'},
  'fortune-slip': {collection:'alley-curios', name:'Fortune slip'},
  'moon-brooch': {collection:'wearables', name:'Moon brooch'},
  'autumn-leaf-lantern': {collection:'seasonal-treasures', name:'Autumn-leaf lantern'},
  'juggling-bird': {collection:'game-prizes', name:'Juggling bird'},
  'patchwork-bear': {collection:'game-prizes', name:'Patchwork bear'},
  'prize-bag': {collection:'gift-wrapping', name:'Prize bag'},
  'memory-camera': {collection:'parlour-prizes', name:'Memory camera'},
  'shutter-click': {collection:'machine-curios', name:'Shutter click'},
  'photo-accordion': {collection:'collector-books', name:'Photo accordion'},
  'lightning-pin': {collection:'game-prizes', name:'Lightning pin'},
  'pegboard-star': {collection:'wonder-prizes', name:'Pegboard star'},
  'mercury-bead': {collection:'machine-curios', name:'Mercury bead'},
  'dairy-calf': {collection:'game-prizes', name:'Dairy calf'},
  'alley-collector-cup': {collection:'awards', name:'Alley collector cup'},
  'perfect-circle': {collection:'game-prizes', name:'Perfect circle'},
  'pressed-flower-book': {collection:'collector-books', name:'Pressed flower book'},
  'flicker-book': {collection:'wonder-prizes', name:'Flicker book'},
  'pocket-peepshow': {collection:'wonder-prizes', name:'Pocket peepshow'},
  'memory-scrapbook': {collection:'collector-books', name:'Memory scrapbook'},
  'moon-rabbit': {collection:'toy-shelf', name:'Moon rabbit'},
  'singing-bird': {collection:'toy-shelf', name:'Singing bird'},
  'dapper-fox': {collection:'toy-shelf', name:'Dapper fox'},
  'mighty-mallet': {collection:'wonder-prizes', name:'Mighty mallet'},
  'bell-of-bravery': {collection:'wonder-prizes', name:'Bell of bravery'},
  'bell-bracelet': {collection:'wearables', name:'Bell bracelet'},
  'looking-glass-locket': {collection:'wonder-prizes', name:'Looking-glass locket'},
  'mirror-shard': {collection:'alley-curios', name:'Mirror shard'},
  'star-fragment': {collection:'future-curios', name:'Star fragment'},
  'lucky-ring-trio': {collection:'wonder-prizes', name:'Lucky ring trio'},
  'splash-ring': {collection:'garden-prizes', name:'Splash ring'},
  'wishing-acorn': {collection:'future-curios', name:'Wishing acorn'},
  'five-penny-stack': {collection:'pennies', name:'Five-penny stack'},
  'ticket-roll': {collection:'tickets', name:'Ticket roll'},
  'fairy-floss': {collection:'sweet-treats', name:'Fairy floss'},
  'pocket-cloud': {collection:'future-curios', name:'Pocket cloud'},
  'cloud-jar': {collection:'wonder-prizes', name:'Cloud jar'},
  'swirl-lolly': {collection:'sweet-treats', name:'Swirl lolly'},
  'popcorn-carton': {collection:'sweet-treats', name:'Popcorn carton'},
  'tiny-kettle': {collection:'garden-prizes', name:'Tiny kettle'},
  'sweet-heat': {collection:'machine-curios', name:'Sweet heat'},
  'showman-pass': {collection:'tickets', name:'Showman pass'},
  'velvet-mask': {collection:'garden-prizes', name:'Velvet mask'},
  'secret-door-key': {collection:'future-curios', name:'Secret door key'},
  'marquee-bulb': {collection:'machine-curios', name:'Marquee bulb'},
  'pocket-marquee': {collection:'garden-prizes', name:'Pocket marquee'},
  'lantern-lighter': {collection:'working-midway', name:'Lantern lighter'},
  'little-sailboat': {collection:'game-prizes', name:'Little sailboat'},
  'star-spectacles': {collection:'wearables', name:'Star spectacles'},
  'music-carousel': {collection:'ride-keepsakes', name:'Music carousel'},
  'organ-music-box': {collection:'ride-keepsakes', name:'Organ music box'},
  'pocket-wheel': {collection:'ride-keepsakes', name:'Pocket wheel'},
  'balloon-bouquet': {collection:'ride-keepsakes', name:'Balloon bouquet'},
  'swing-spinner': {collection:'ride-keepsakes', name:'Swing spinner'},
  'gyro-ghost': {collection:'machine-curios', name:'Gyro ghost'},
  'first-visit-badge': {collection:'awards', name:'First-visit badge'},
  'kindness-heart': {collection:'awards', name:'Kindness heart'},
  'perfect-play-medal': {collection:'awards', name:'Perfect-play medal'},
  'ride-explorer-pennant': {collection:'awards', name:'Ride-explorer pennant'},
  'aura-keepsake': {collection:'awards', name:'Aura keepsake'},
  'midway-master-crown': {collection:'awards', name:'Midway-master crown'},
  'cocoa-cup': {collection:'sweet-treats', name:'Cocoa cup'},
  'toffee-apple': {collection:'sweet-treats', name:'Toffee apple'},
  'lemon-fizz': {collection:'sweet-treats', name:'Lemon fizz'},
  'picnic-parcel': {collection:'sweet-treats', name:'Picnic parcel'},
  'button-elephant': {collection:'toy-shelf', name:'Button elephant'},
  'crown-turtle': {collection:'toy-shelf', name:'Crown turtle'},
  'sleepy-dragon': {collection:'toy-shelf', name:'Sleepy dragon'},
  'tin-style-robot': {collection:'toy-shelf', name:'Tin-style robot'},
  'pocket-theatre': {collection:'toy-shelf', name:'Pocket theatre'},
  'birthday-crown-box': {collection:'seasonal-treasures', name:'Birthday crown box'},
  'moon-festival-fan': {collection:'seasonal-treasures', name:'Moon-festival fan'},
  'winter-snow-globe': {collection:'seasonal-treasures', name:'Winter snow globe'},
  'spring-seed-packet': {collection:'seasonal-treasures', name:'Spring seed packet'},
  'summer-sun-pin': {collection:'seasonal-treasures', name:'Summer sun pin'},
  'spooky-pumpkin-friend': {collection:'seasonal-treasures', name:'Spooky pumpkin friend'},
  'new-year-star-cracker': {collection:'seasonal-treasures', name:'New-year star cracker'},
  'midway-scarf': {collection:'wearables', name:'Midway scarf'},
  'paper-crown': {collection:'wearables', name:'Paper crown'},
  'friendship-pins': {collection:'wearables', name:'Friendship pins'},
  'fortune-journal': {collection:'collector-books', name:'Fortune journal'},
  'ride-stamp-book': {collection:'collector-books', name:'Ride stamp book'},
  'charm-display-case': {collection:'collector-books', name:'Charm display case'},
  'curio-cabinet-album': {collection:'collector-books', name:'Curio cabinet album'},
  'midnight-invitation': {collection:'future-curios', name:'Midnight invitation'},
  'sleepy-compass': {collection:'future-curios', name:'Sleepy compass'},
  'bullseye-clock': {collection:'garden-prizes', name:'Bullseye clock'},
  'crystal-cradle': {collection:'parlour-prizes', name:'Crystal cradle'},
  'garden-party-book': {collection:'paper-doll-books', name:'Garden-party book'},
  'seaside-day-book': {collection:'paper-doll-books', name:'Seaside-day book'},
  'winter-lantern-book': {collection:'paper-doll-books', name:'Winter-lantern book'},
  'moonlight-wardrobe': {collection:'paper-doll-books', name:'Moonlight wardrobe'},
  'stamp-passport': {collection:'tickets', name:'Stamp passport'},
  'prize-claim': {collection:'tickets', name:'Prize claim'},
  'ride-ticket': {collection:'tickets', name:'Ride ticket'},
  'midway-map': {collection:'tickets', name:'Sideshow alley map'},
  'lost-and-found-tag': {collection:'working-midway', name:'Lost-and-found tag'},
  'stamp-and-inkpad': {collection:'working-midway', name:'Stamp and inkpad'},
  'ticket-punch': {collection:'working-midway', name:'Ticket punch'},
  'ribbon-gift-box': {collection:'gift-wrapping', name:'Ribbon gift box'},
  'surprise-parcel': {collection:'gift-wrapping', name:'Surprise parcel'},
  'treasure-tin': {collection:'gift-wrapping', name:'Treasure tin'},
  'crown-hatbox': {collection:'doll-accessories', name:'Crown hatbox'},
  'laughing-doorway': {collection:'ride-keepsakes', name:'Laughing doorway'},
  'showman-ribbon': {collection:'alley-curios', name:'Showman ribbon'},
  'coin-album': {collection:'pennies', name:'Coin album'},
};

export const spriteKey = id => {
  const item = items[id];
  return item ? item.collection+'/'+id : id;
};
export const itemName = id => items[id]?.name || id;
export const kits = {
  'coin-pusher': {
    sprites: ['everyday-penny','penny-purse','moon-penny','rose-penny','star-token','crown-token','pressed-heart','lucky-match','looking-glass-locket','clockwork-butterfly','secret-door-key','moon-brooch','crystal-cradle','star-fragment','wishing-acorn','pocket-cloud','mercury-bead','gyro-ghost','aura-keepsake','midnight-invitation','sleepy-compass','clockwork-key','heart-gear'],
    prizes: ['coin-sleeve','copper-cascade','penny-tree','coin-album','treasure-tin','five-penny-stack'],
  },
  whisper: {
    sprites: ['trade-envelope','sealed-secret','return-postcard','message-bottle','charm-pouch'],
    prizes: ['whisper-charm','charm-pouch','secret-keeper','surprise-parcel','stamp-passport','lost-and-found-tag'],
  },
  pack: {
    sprites: ['night-suitcase','ticket-satchel','penny-purse','coin-sleeve','lucky-match','whisper-charm','pocket-observatory'],
    prizes: ['pressed-heart','penny-purse','penny-collector-book','treasure-tin','midnight-invitation','ticket-satchel'],
  },
  love: {
    sprites: ['pressed-heart','heart-biscuit','rose-penny','rose-lockbox'],
    prizes: ['rose-hair-bow','rose-press','rose-lockbox','kindness-heart','friendship-pins','ribbon-gift-box'],
  },
  curios: {
    sprites: ['clockwork-key','cabinet-key','heart-gear','display-dome','clockwork-butterfly'],
    prizes: ['clockwork-key','display-dome','clockwork-butterfly','tin-style-robot','crystal-cradle','curio-cabinet-album'],
  },
  'duck-pond': {
    sprites: ['crowned-duck'],
    prizes: ['brave-try-ribbon','lucky-dish','crowned-duck','sleepy-dragon','spooky-pumpkin-friend','crown-turtle'],
  },
  fortune: {
    sprites: ['moon-lantern','fortune-slip','moon-penny','moon-brooch'],
    prizes: ['fortune-slip','moon-penny','moon-brooch','fortune-journal','moon-festival-fan','paper-crown'],
  },
  'ball-toss': {
    sprites: ['autumn-leaf-lantern','moon-lantern'],
    prizes: ['juggling-bird','patchwork-bear','prize-bag','button-elephant','prize-claim','midway-scarf'],
  },
  snap: {
    sprites: ['memory-camera','shutter-click'],
    prizes: ['shutter-click','photo-accordion','memory-camera','ride-stamp-book','first-visit-badge','pocket-theatre'],
  },
  pinball: {
    sprites: ['lightning-pin','everyday-penny','star-token','moon-penny','rose-penny','crown-token','pegboard-star','summer-sun-pin','bullseye-clock','looking-glass-locket','penny-purse'],
    prizes: ['lightning-pin','star-token','pegboard-star','summer-sun-pin','bullseye-clock','looking-glass-locket'],
  },
  'milk-bottles': {
    sprites: ['message-bottle','mercury-bead','dairy-calf','lucky-dish','alley-collector-cup','cocoa-cup','crown-hatbox','button-elephant','penny-purse','everyday-penny'],
    prizes: ['dairy-calf','lucky-dish','alley-collector-cup','cocoa-cup','crown-hatbox','button-elephant'],
  },
  'cover-the-spot': {
    sprites: ['moon-penny','rose-penny','star-token'],
    prizes: ['perfect-circle','pressed-flower-book','lucky-dish','spring-seed-packet','garden-party-book','charm-display-case'],
  },
  mutoscope: {
    sprites: ['moon-rabbit','singing-bird','dapper-fox','moon-lantern','trade-envelope','cabinet-key'],
    prizes: ['flicker-book','pocket-peepshow','memory-scrapbook','moonlight-wardrobe','charm-display-case','pocket-theatre'],
  },
  'high-striker': {
    sprites: ['mighty-mallet','bell-of-bravery','mercury-bead'],
    prizes: ['mighty-mallet','bell-bracelet','bell-of-bravery','perfect-play-medal','midway-master-crown','ride-explorer-pennant'],
  },
  catoptromancy: {
    sprites: ['moon-lantern','star-fragment'],
    prizes: ['looking-glass-locket','mirror-shard','star-fragment','winter-snow-globe','winter-lantern-book','sleepy-compass'],
  },
  'bent-rings': {
    sprites: ['wishing-acorn','lucky-ring-trio'],
    prizes: ['lucky-ring-trio','splash-ring','wishing-acorn','crown-turtle','paper-crown','friendship-pins'],
  },
  plinko: {
    sprites: ['pressed-heart','star-token','moon-penny','lucky-dish'],
    prizes: ['five-penny-stack','lucky-dish','mercury-bead','ticket-punch','stamp-and-inkpad','coin-album'],
  },
  'fairy-floss': {
    sprites: ['fairy-floss','swirl-lolly','pocket-cloud','heart-biscuit'],
    prizes: ['fairy-floss','pocket-cloud','cloud-jar','toffee-apple','cocoa-cup','birthday-crown-box'],
  },
  popcorn: {
    sprites: ['popcorn-carton','tiny-kettle','sweet-heat'],
    prizes: ['popcorn-carton','tiny-kettle','sweet-heat','picnic-parcel','lemon-fizz','toffee-apple'],
  },
  'skee-ball': {
    sprites: ['moon-penny','star-token'],
    prizes: ['moon-penny','star-token','pegboard-star','ride-ticket','ride-stamp-book','summer-sun-pin'],
  },
  'penny-pitch': {
    sprites: ['everyday-penny','moon-penny'],
    prizes: ['five-penny-stack','moon-penny','wishing-acorn','coin-album','stamp-passport','prize-claim'],
  },
  'dunk-tank': {
    sprites: ['crowned-duck','mercury-bead'],
    prizes: ['splash-ring','crowned-duck','dairy-calf','laughing-doorway','seaside-day-book','lemon-fizz'],
  },
  marquee: {
    sprites: ['marquee-bulb','pocket-marquee','star-token','moon-penny','pressed-heart'],
    prizes: ['marquee-bulb','pocket-marquee','lantern-lighter','midway-map','aura-keepsake','ride-ticket'],
  },
  pass: {
    sprites: ['secret-door-key','velvet-mask'],
    prizes: ['showman-pass','velvet-mask','secret-door-key','showman-ribbon','pocket-theatre','midnight-invitation'],
  },
  lookup: {
    sprites: ['star-fragment','star-spectacles','pocket-observatory','moon-rabbit','dapper-fox','moon-lantern'],
    prizes: ['star-fragment','pocket-observatory','star-spectacles','sleepy-compass','midnight-invitation','aura-keepsake'],
  },
  'water-gun': {
    sprites: ['little-sailboat','trade-envelope','message-bottle'],
    prizes: ['little-sailboat','message-bottle','splash-ring','seaside-day-book','picnic-parcel','stamp-passport'],
  },
  carousel: {
    sprites: ['music-carousel','organ-music-box','pocket-wheel','swing-spinner','gyro-ghost','star-token'],
    prizes: ['music-carousel','organ-music-box','pocket-wheel','laughing-doorway','ride-explorer-pennant','ride-ticket'],
  },
  balloons: {
    sprites: ['balloon-bouquet','autumn-leaf-lantern','moon-lantern','prize-bag'],
    prizes: ['balloon-bouquet','prize-bag','swing-spinner','birthday-crown-box','friendship-pins','paper-crown'],
  },
};
